# Generated by Django 5.1.3 on 2024-11-23 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Birth_Certificate', models.FileField(upload_to='documents/')),
                ('KCPE_Result_Slip', models.FileField(upload_to='documents/')),
                ('Leaving_Certificate', models.FileField(upload_to='documents/')),
                ('Medical_Examination_Form', models.FileField(upload_to='documents/')),
                ('Fee_Payment_Receipt', models.FileField(upload_to='documents/')),
                ('certificate_of_Good_Conduct', models.FileField(upload_to='documents/')),
                ('passport', models.ImageField(blank=True, default='', upload_to='')),
                ('photo_id', models.ImageField(blank=True, default='', upload_to='')),
                ('intake', models.ForeignKey(choices=[('J', 'January Intake'), ('A', 'April Intake'), ('S', 'September Intake')], default='S', on_delete=django.db.models.deletion.CASCADE, to='ELEARNING.intake')),
            ],
        ),
    ]
