# Generated by Django 5.1.3 on 2024-11-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ELEARNING', '0002_intake_address_intake_city_intake_dob_intake_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='passport',
            field=models.ImageField(blank=True, upload_to='document/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='photo_id',
            field=models.ImageField(blank=True, upload_to='document/'),
        ),
    ]
